### ISSUE TITLE
Adaptive QoS is missing since 5.1.0

### ISSUE THREAD

**Issue by grockk** [MerlinRdev/bluecave-merlin#15]
Great work adding features. I don't have skills to contribute except for quality testing like this.

The adaptive QoS feature for the BlueCave seams to be missing in the GUI. I can't tell if it is still working after setting it up in previous version but can't configure and the page doesn't load.

Under the Traffic Manager there should be an option for adaptive QoS in the QoS type but it is absent. It's this page. http://router.asus.com/QoS_EZQoS.asp

Also there is a secret traffic configuration page at http://router.asus.com/AdaptiveQoS_Bandwidth_Monitor.asp that works in 5.1.0 but seems to be missing in new firmwares..

There's about 4MB difference since 5.1.0 so looks like it may be missing from newest firmware.

**Comment by chongaik3** [comment]
@grockk Thanks! I did not know there is a secret traffic configuration page!!! Any more secret page?

I am still using Ver5.1.0 because i also noticed from Ver 5.1.1 many features likes Adaptive QoS and Time Scheduling feature are missing or reduced.

However, Adaptive QoS is there (not on dedicated Tab) on Ver 5.1.0 (see print screen below) and i am able to configure it .
![image](https://user-images.githubusercontent.com/65849541/92319104-b51ad400-f047-11ea-9822-d3cb26609034.png)

I'm not sure are you is this what you are looking for on Ver 5.1.0? I am not sure is these features are removed or missed out on newer version. Maybe @paldier has the answers and thanks for his great effort to provide alternative firmware for Blue Cave.

**Comment by paldier** [comment]
asus drop it

**Comment by grockk** [comment]
Oh man. I did a search and see a lot of threads on reddit and elsewhere that they removed it from the official firmware. what a bummer. Is there any way you can restore that functionality?

**Comment by paldier** [comment]
No, i can't do that until asus update sdk to 7.5, some bugs has been fixed in 7.5, let us wait for the 386 firmware

**Comment by grockk** [comment]
Ok. Thanks so much.

**Comment by paldier** [comment]
asus readd Adaptive QoS in latest firmware

**Comment by paldier** [comment]
https://dlcdnets.asus.com/pub/ASUS/wireless/Blue_Cave/FW_BLUECAVE_900438446629.zip

**Comment by chongaik3** [comment]
@paldier Thanks for sharing.

**Comment by grockk** [comment]
Same version when i downloaded as well.  BLUECAVE_9.0.0.4_384_46629-g481b3fb.trx. That's weird.

**Comment by chongaik3** [comment]
> Same version when i downloaded as well. BLUECAVE_9.0.0.4_384_46629-g481b3fb.trx. That's weird.
> 
> But can confirm adaptive QoS is back in this firmware, regardless of build numbers weirdness.

If not mistaken, Dual WAN feature still missing. I remember i saw a post mentioning that Blue Cave do support Dual WAN.

**Comment by paldier** [comment]
> 
> 
> > Same version when i downloaded as well. BLUECAVE_9.0.0.4_384_46629-g481b3fb.trx. That's weird.
> > But can confirm adaptive QoS is back in this firmware, regardless of build numbers weirdness.
> 
> If not mistaken, Dual WAN feature still missing. I remember i saw a post mentioning that Blue Cave do support Dual WAN.

Yeah, new sdk 7.5 support dual wan and link aggregation, but asus has been staying in 7.4
